### ISSUE TITLE
Acesso ao webacula e bdashboard

### ISSUE THREAD

**Issue by renatorsti** [PoP-PR/bacula#2]
Bom dia;

Estou com tendo difilcudade para logar na ferramenra, eu ate consigo chegar nas telas de login porem não consigo logar;
Gostaria de uma ajuda,
segue meu skype e email;
### Skype: renators.ti
Email: renators.ti@gmail.com

**Comment by tjapa** [comment]
Bom dia, Renato.

O login do bdashboard é "admin", a senha é "bacula".
Havia um problema na imagem do Webacula, o repositório do github e a imagem do docker hub foram atualizadas.
É possível que o webacula contenha problemas, pois é uma ferramenta muito antiga, mas caso queira usar mesmo assim, o login é "root" e a senha é "bacula".
